services:
  sales-database: # Service names
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
    container_name: sales-app-db  # Container names
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales  # Database names
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - sales-database:/opt/msTest/data

  sales-management:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    container_name: sales-management
    depends_on:
      sales-database:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  sales-database: