spring:
  application:
    name: user-management

datasource:
  shard0:
    jdbc-url: jdbc:postgresql://localhost:5432/shard0db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  shard1:
    jdbc-url: jdbc:postgresql://localhost:5433/shard1db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  shard2:
    jdbc-url: jdbc:postgresql://localhost:5434/shard2db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  
logging:
  level:
    org.springframework: DEBUG